# Generated by Django 5.1.15 on 2026-09-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assessment', 'Skill Assessment'), ('roadmap', 'AI Learning Roadmap'), ('interview', 'Interview Prep'), ('resume', 'Resume Analysis'), ('system', 'System Alert')], default='system', max_length=30),
        ),
    ]
