# Generated by Django 5.1.15 on 2026-09-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='question_count',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
