# Generated by Django 6.1.1 on 2026-09-25 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'SkillNova AI Assistant')], default='user', max_length=20)),
                ('message', models.TextField()),
                ('code_snippet', models.TextField(blank=True, default='')),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('practice_question', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='General', max_length=120)),
                ('difficulty', models.CharField(default='Intermediate', max_length=30)),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_option', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True, default='')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='accounts.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=150)),
                ('experience_level', models.CharField(default='Fresher', max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('questions', models.JSONField(default=list, help_text='Generated questions: [{id, category: technical|conceptual|scenario|project|hr, question, expected_concepts}]')),
                ('answers', models.JSONField(default=dict, help_text='Student answers: {question_id: answer_text}')),
                ('evaluation', models.JSONField(default=list, help_text='Evaluation per question: [{question_id, score, feedback, missing_concepts, tips}]')),
                ('overall_feedback', models.TextField(blank=True, default='')),
                ('overall_score', models.FloatField(default=0.0)),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
