# Generated by Django 6.1.1 on 2026-09-25 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('target_role', models.CharField(max_length=150)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('detected_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('match_percentage', models.FloatField(default=0.0)),
                ('education_detected', models.JSONField(default=list)),
                ('projects_detected', models.JSONField(default=list)),
                ('experience_detected', models.JSONField(default=list)),
                ('tools_detected', models.JSONField(default=list)),
                ('recommended_learning_path', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
